# ChatGPT API key,需要前往OpenAI我的里面获取
apiKey: ""

# 回复结果的最大 tokens 数量，根据模型所定，有的最大2048，有的 4096，根据官网 tokenizer 描述，对于普通英文文本，100 个 tokens 差不多等于 75 个单词，具体计算规则可查看 platform.openai.com/tokenizer
maxTokens: 4000

# 控制生成的文本的多样性。值越高，生成的文本就越多样，并且更具创意性。值越低，生成的文本就越保守，更符合逻辑。
topP: 0.9

# 控制生成的文本的随机性。值越高，生成的文本就越随机，更具创意性。值越低，生成的文本就越保守，更符合逻辑。值为 0 时，生成的文本就是模型的预测结果，不会有任何随机性。值为 1 时，生成的文本就是随机的，不会有任何逻辑性。
temperature: 0.2
